### ISSUE TITLE
edda build

### ISSUE THREAD

**Issue by ctippur** [Netflix/edda#113]
Hello,

This is more a question than a issue.
I have followed https://github.com/Netflix/edda/wiki/Quick-Start-Guide and ran buildViaTravis.sh on a mac laptop.

I think the build was successful -
[info] All tests passed.
[success] Total time: 47 s, completed 15-Feb-2017 08:02:46
[info] all files have correct license header
[success] Total time: 0 s, completed 15-Feb-2017 08:02:46

Wondering what I need to do next. Is there a specific document I need to follow to get the installation to work and get jetty running?

Appreciate your inputs.

- S

**Comment by brharrington** [comment]
Have you tried using [jettyRun](https://github.com/Netflix/edda/wiki/Quick-Start-Guide#Run_Edda_with_Gradle)? Are you seeing any specific errors?
