### ISSUE TITLE
I added in New Regions which fail to authenticate

### ISSUE THREAD

**Issue by efreedom79** [Netflix/edda#123]
The error is:

com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 784076F1E98745AC, AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256., S3 Extended Request ID: dVjKGfS8GwbeyPwvkBqVZ+OFcYzgw5YUl8erHWdoMRZ9gXkKEtHzdTqIZa/rGT3IWlsXUKrGQE4=

The old regions work, some of the new ones don't. Specifically us-east-2, eu-west-2, eu-west-3, eu-central-1 seem to fail.

AWS says 
"Past a member of our S3 support team who stated he had seen similar errors in the past. For those it was usually related to using older versions of our code signing signature in new regions. A break down of which regions support which versions of the signature can be found here: https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.aws.amazon.com_general_latest_gr_rande.html-23s3-5Fregion&d=DwICaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=nHtjxYB2z8kPeV8bKkS2HKIYxOgz4isoxyTRvFzRWsAF_5OCaT8sVtGmeamSMNn2&m=I-w_2SxO7FOZj3O-3d9ZjbSQjlU56krE8TZ1nfOPTT4&s=XSo8F2lKRitvPjwzdQfFuGg0r3SFvzvFj7w9rOPbT3A&e"

and that the software application needs to be updated.

What version does the software need to be upgraded to use "signature-4" authentication?

Bob

**Comment by brharrington** [comment]
> What version does the software need to be upgraded to use "signature-4" authentication?

I don't know what version of the SDK added those changes, but we should be able to just update to the latest.
