### ISSUE TITLE
AWS api requests amount

### ISSUE THREAD

**Issue by drax68** [Netflix/edda#77]
Hi, is there a way to throttle requests/reduce requests amount, so other apps that using api under same account will not suffer from aws-initiated throttling?

**Comment by pparth** [comment]
Anything new about this please?

**Comment by brharrington** [comment]
I recently inherited this project and am still getting familiar with some of the aspects. As far as I know there is no way to tune the request rate right now.

**Comment by brharrington** [comment]
Should be fixed with #96.
